### ISSUE TITLE
Fails after running lssystem on SV 8.1.3.5

### ISSUE THREAD

**Issue by robinsg** [IBM/SVCheck#2]
I'm executing:

$ ./SVCheck -i 172.xxx.yyy.zzz -u superuser -v

but this fails after attempting to send the lssystem command:

 Welcome Spectrum Virtualize Checker (SVCheck) version 1.0

 It generates an Excel file Spectrum Virtualize system with relevant information of current status using the API

 Please read the README.md file that comes with this tool
 Please check https://github.com/IBM/SVCheck the latest information about this tool

 This tool comes with no warranty of anykind, use at your own risk

Do you want to continue? (y/n): y
2020-05-12 09:10:08,066 DEBUG:   Starting check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,105 DEBUG:   Completed check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,106 DEBUG:   Getting auth token from 172.100.200.210
2020-05-12 09:10:08,117 DEBUG:   Starting new HTTPS connection (1): 172.100.200.210:7443
2020-05-12 09:10:08,343 DEBUG:   https://172.100.200.210:7443 "POST /rest/auth HTTP/1.1" 200 77
2020-05-12 09:10:08,346 INFO:    Got valid auth token from 172.100.200.210
2020-05-12 09:10:08,346 DEBUG:   Going to query role of superuser
2020-05-12 09:10:08,346 DEBUG:   Starting check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,364 DEBUG:   Completed check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,364 DEBUG:   Checking user superuser has appropiate role for command lscurrentuser
2020-05-12 09:10:08,365 DEBUG:   All groups can run lscurrentuser
2020-05-12 09:10:08,365 DEBUG:   Going to send command run lscurrentuser to API
2020-05-12 09:10:08,367 DEBUG:   Starting new HTTPS connection (1): 172.100.200.210:7443
2020-05-12 09:10:08,553 DEBUG:   https://172.100.200.210:7443 "POST /rest/lscurrentuser HTTP/1.1" 200 55
2020-05-12 09:10:08,554 DEBUG:   Got HTTP 200 on command run lscurrentuser to API
2020-05-12 09:10:08,555 DEBUG:   Got role of superuser is SecurityAdmin
2020-05-12 09:10:08,558 DEBUG:   Gathering lssystem information from 172.100.200.210
2020-05-12 09:10:08,559 DEBUG:   Starting check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,576 DEBUG:   Completed check access to API port 172.100.200.210:7443
2020-05-12 09:10:08,577 DEBUG:   Checking user superuser has appropiate role for command lssystem
2020-05-12 09:10:08,577 DEBUG:   All groups can run lssystem
2020-05-12 09:10:08,577 DEBUG:   Going to send command run lssystem to API
2020-05-12 09:10:08,580 DEBUG:   Starting new HTTPS connection (1): 172.100.200.210:7443
2020-05-12 09:10:08,786 DEBUG:   https://172.100.200.210:7443 "POST /rest/lssystem HTTP/1.1" 200 None
2020-05-12 09:10:08,787 DEBUG:   Got HTTP 200 on command run lssystem to API
Traceback (most recent call last):
  File "./SVCheck", line 162, in <module>
    main()
  File "./SVCheck", line 156, in main
    my_system.generate_excel_report()
  File "/home/robinsg/SVCheck/classes/SV_utils.py", line 97, in generate_excel_report
    self.__parse_command_to_excel(command)
  File "/home/robinsg/SVCheck/classes/SV_utils.py", line 271, in __parse_command_to_excel
    cmd_list = self.__format_lssystem_to_excel()
  File "/home/robinsg/SVCheck/classes/SV_utils.py", line 235, in __format_lssystem_to_excel
    "Quorum lease": lssystem['quorum_lease'],
KeyError: 'quorum_lease'

python - v3.6.9
requests - v2.23.0
pandas - v1.0.3
openpyxl - v3.0.3

**Comment by bolinches** [comment]
Thanks.

Should be fixed on the next push. The point is to get the minimum common values for all systems and releases, so we might hit a few more of this for lssystem. The other commands are different as they are imported as-is to Excel. Unless those start reporting more than 1 dimensions values
